name: Manual Run

on:
  workflow_dispatch:
    inputs:
      TEST_FILE:
        description: 'Select test files to run'
        required: true
        default: 'MyFirstTest'
        type: choice
        options:
          - TestCases/RowTypes/LinearRows/CHD1Rows
          - TestCases/RowTypes/LinearRows/EPG1Rows

      DEVICE_ID:
        description: 'Select device to run'
        required: true
        default: 'd740d673-34bb-4238-844d-985a8b7e0efa'
        type: choice
        options:
          - d740d673-34bb-4238-844d-985a8b7e0efa
          - TestCases/RowTypes/LinearRows/CHD1Rows    

jobs:
  run-suitest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install Suitest CLI globally
      run: npm install -g suitest-js-api  

    - name: Run Suitest test
      run: |
        suitest run \
          --token-id ${{ secrets.SUITEST_TOKEN_ID }} \
          --token-password ${{ secrets.SUITEST_TOKEN_PASSWORD }} \
          --app-config-id e068c84f-9d52-4f57-a6e4-16dc0fcb9ba9 \
          --device-id ${{ secrets.DEVICE_ID }} \
          node ./${{ inputs.TEST_FILE }}.js

