name: Schedule test pack Run

on:
  workflow_dispatch:
    inputs:
      TEST_PACK_ID:
        description: 'Select test pack'
        required: true
        default: '30983'
        type: choice
        options:
          - 30983
          - 30984

jobs:
  run-suitest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Suitest test pack
      run: |
        curl -X POST https://the.suite.st/api/public/v4/test-packs/${{ inputs.TEST_PACK_ID }} \
          -H 'Content-Type: application/json' \
          -H 'X-TokenId: ${{ secrets.SUITEST_TOKEN_ID }}' \
          -H 'X-TokenPassword: ${{ secrets.SUITEST_TOKEN_PASSWORD }}' \
          -d '{"includeChangelist": false}'       
